swagger: '2.0'
info:
  version: 3.0.3
  title: flavor
  description: |-
  
    The flavor specifies elementary information about the compute
    node, such as memory and number of cores, as well as other
    attributes that can be added. Flavors are essential to size a
    virtual cluster appropriately.

    x-date: 10-30-2018

  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: Cloudmesh RESTful Service Example
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
    url: https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt
host: 'localhost:8080'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/flavors:
    get:
      description: Returns all flavors
      operationId: flavor.get_flavor
      produces:
        - application/json
      responses:
        '200':
          description: flavor info
          schema:
            $ref: '#/definitions/Flavor'
    put:
      summary: Create a new flavor
      operationId: flavor.add_flavor
      parameters:
        - in: body
          name: flavor
          description: The new flavor to create
          schema:
            $ref: '#/definitions/Flavor'
      responses:
        '201':
          description: Created
  '/cloudmesh/flavor/{name}':
    get:
      description: Returns a flavor
      operationId: flavor.get_flavor_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: flavor info
          schema:
            $ref: '#/definitions/Flavor'
definitions:
  Flavor:
    type: object
    description: the flavor
    properties:
      name:
        type: string
        description: name of the flavor
      id:
        type: string
        description: the id of the flavor
      label:
        type: string
        description: a label that a user can set for this flavor
      metadata: 
        type: string
        description: A dictionary with additional metadata
      uuid:
        type: string
        description: the uuid of the flavor
      ram:
        type: integer
        description: number of bytes used for the image in RAM
      disk:
        type: integer
        description: number of bytes used for the disk
      price:
        type: string
        description: price for the flavor
      cloud:
        type: string
        description: name of the cloud this flavor is used
      cloud_id:
        type: string
        description: an id used by the cloud

